### ISSUE TITLE
Somethign wrong with project

### ISSUE THREAD

**Issue by bennylame** [vercel/next-learn-starter#26]
Hey, 

I was just trying to follow a guide for dynamic routing but I get errors when running: ```npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/dynamic-routes-starter"```

This is my error log: 

```> npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/dynamic-routes-starter"
Creating a new Next.js app in /Users/<User>/Code/Learning/nextjs-blog.

Downloading files from repo https://github.com/vercel/next-learn-starter/tree/master/dynamic-routes-starter. This might take a moment.

Installing packages. This might take a couple of minutes.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@"^16.6.0 || ^17" from next@10.0.1
npm ERR!   node_modules/next
npm ERR!     next@"^10.0.0" from the root project
npm ERR!   3 more (react-dom, @next/react-dev-overlay, styled-jsx)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0" from use-subscription@1.5.0
npm ERR! node_modules/next/node_modules/use-subscription
npm ERR!   use-subscription@"1.5.0" from next@10.0.1
npm ERR!   node_modules/next
npm ERR!     next@"^10.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.````

These are my installed versions of npm, npx and node:

> npm -v
7.0.8

> npx -v
7.0.8

> node -v
v15.1.0

**Comment by lewisrobbins** [comment]
Also having the same issue. I'm following this tutorial: https://nextjs.org/learn/basics/create-nextjs-app/setup

@vercel

**Comment by mxa0079** [comment]
This should be solved by https://github.com/vercel/next-learn-starter/pull/24

**Comment by meowthing** [comment]
I've tried to update my react packages to the latest ver but that didn't solve anything.

**Comment by lewisrobbins** [comment]
Can we get #24 merged?

**Comment by leerob** [comment]
I'm taking care of the package updates now! Thank you all so much.

**Comment by leerob** [comment]
https://github.com/vercel/next-learn-starter/pull/23 was merged, resolving the issues.
